### ISSUE TITLE
Current build fails with KeyError "status" due to requirements changes

### ISSUE THREAD

**Issue by DavidHuebner** [averbis/IRuta#21]
**To Reproduce**
1. Install the IRuta kernel as described in the README.md
2. Start a notebook and execute a UIMA Ruta cell in a SoS Notebook

**Expected behavior**
It should work again.

**Error message**
```
Traceback (most recent call last):
  File "/home/iruta/temp/IRuta/venv/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 398, in dispatch_shell
    await result
  File "/home/iruta/temp/IRuta/venv/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 735, in execute_request
    metadata = self.finish_metadata(parent, metadata, reply_content)
  File "/home/iruta/temp/IRuta/venv/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 220, in finish_metadata
    metadata["status"] = reply_content["status"]
KeyError: 'status'
```

**Additional context**
We should probably all dependencies, especially sos-notebook

**Comment by DavidHuebner** [comment]
The problems seems to be the transitive update of jupyter-core to version 5
